# Site settings
title: Moritz Lürig | Personal website
description: >- # site description
  Personal website of Dr. Moritz D. Lürig. 
lang: en-US # default lang
timezone: Europe/Berlin # set your timezone
# image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/mluerig/personal-homepage # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Moritz Lürig # author name
  email: moritz.luerig@gmail.com # email adress
  avatar: /assets/images/moritz_luerig_portrait.jpg # change with your own avatar


# URL settings
url: "https://www.luerig.net" #
baseurl:
permalink: /posts/:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  parse_block_html: false
  auto_ids: true

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

      
# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:
    
# jekyll-archives:
  # enabled:
    # - year
    # - categories
    # - tags
  # layout: archive
  # permalinks:
    # year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    # tag: '/tag/:name/'
    # category: '/category/:name/'

# Homepage limit posts
number_of_posts: 5

sass:
  style: compressed
  quiet_deps: true
  
include:
  - _redirects
  - .htaccess
  - _pages
  
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-postfiles
  - jemoji
  - jekyll-archives
